# Generated by Django 2.1.3 on 2020-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_administrador', models.CharField(max_length=50)),
                ('rut_administrador', models.CharField(max_length=12)),
            ],
            options={
                'permissions': (('administrador', 'Es administrador'),),
            },
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id_bodeguero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_bodeguero', models.CharField(max_length=50)),
                ('rut_bodeguero', models.CharField(max_length=12)),
            ],
            options={
                'permissions': (('bodeguero', 'Es bodeguero'),),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('rut_cliente', models.CharField(max_length=12)),
            ],
            options={
                'permissions': (('cliente', 'Es cliente'),),
            },
        ),
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('id_cocinero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cocinero', models.CharField(max_length=50)),
                ('rut_cocinero', models.CharField(max_length=12)),
            ],
            options={
                'permissions': (('cocinero', 'Es cocinero'),),
            },
        ),
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('id_financiera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_financiera', models.CharField(max_length=50)),
                ('rut_financiera', models.CharField(max_length=12)),
            ],
            options={
                'permissions': (('financiera', 'Es financiera'),),
            },
        ),
    ]
